name: Reusable workflow

on: 
  workflow_call:
    inputs: 
      who-to-greet:
        description: "A name to greet"
        default: World
        type: string
    outputs:
      current-time:
        description: "The time"
        value: ${{ jobs.reusable-job.outputs.current-time }}
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet person
        run: echo ${{ inputs.who-to-greet }}
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
